### ISSUE TITLE
enchant don't apply to crosbow

### ISSUE THREAD

**Issue by JellyRoad** [DistortedKey/Higher-Enchants#1]
![Uploading Zrzut ekranu (1469).png…]()

**Comment by DistortedKey** [comment]
looks like I tagged crossbows incorrectly, should be fixed now, I will update the releases, but here is the updated datapack
[higherenchants-1.20.4-v1.1.zip](https://github.com/DistortedKey/Higher-Enchants/files/13767621/higherenchants-1.20.4-v1.1.zip)
